### ISSUE TITLE
How do i Change the Game files location??

### ISSUE THREAD

**Issue by ThomasPoloBelgini** [loriswit/rlcm#4]
when I try to use the button "Enable training room", it appears: "an Error occurred: it was not possible to find a part of the Path".

And I don't know how to solve this, because there is no button saying anything about changing the location of the game files.
Can someone help me please?

(i used Google Translator)

![image](https://github.com/loriswit/rlcm/assets/103902330/9a4abee8-5c8f-4b04-8e7c-7e890b06408c)

**Comment by loriswit** [comment]
RLCM goes through the Windows registry to figure out the game's location. If this fails for some reason, RLCM looks for a process named "Rayman Legends.exe" and uses the location of this program.

This means that, to change the location of the game files, you simply have to launch the game while RLCM is running. Note that the location is being saved permanently, which means that if you restart RLCM, it will use the same location as the last time (that is, until you launch the game from a different directory).

---

About the error you're getting, I have no idea why this would happen. By looking at the path in the message, it looks like you have a pirated version of Rayman Legends, which may not be supported by RLCM (and I don't plan to add support for pirated versions).

If you don't think this error is due to the game being pirated, could you please provide a screenshot showing the content of this folder?

```
E:\Sonic Fan Games\Games\Rayman.Legends-RELOADED\Rayman Legends\
```

**Comment by ThomasPoloBelgini** [comment]
BRO, THANK YOU!! it worked, I just needed this part of your comment to solve:
MAN, THANK YOU!! it worked, I just needed this part of your comment to solve:
![image](https://github.com/loriswit/rlcm/assets/103902330/e51e9e39-0e98-4fb7-bee1-b1e501198b26)

I was getting this error because the game was saved in this folder (E:\Sonic Fan Games\Games\Rayman.Legends-RELOADED\Rayman Legends\), and that was my hard drive, and,
it ended up giving an error and stopped working and I ended up losing this whole folder (E:\Sonic Fan Games); But now I changed it to an SSD and created a new folder for the game with a different path and a different name. the reason for my mistake.

and if you still want a screenshot of the game folder, here it is:
![image](https://github.com/loriswit/rlcm/assets/103902330/5118e7bb-be21-4e4e-ba2f-f6ad3574b056)

**Comment by ThomasPoloBelgini** [comment]
bro, wait, i reopened the issue, because i have a doubt, which maybe could be an error too. Do you know the painting "GoingUp"?, so, when i enter it, nothing appears in the selection of challenges. how do i make the painting "GoingUp" work and make his challenges appear?

**Comment by loriswit** [comment]
> But now I changed it to an SSD and created a new folder for the game with a different path and a different name. that's the reason for the error

Indeed, that's a mistake on my part. I didn't handle the case where the game files would be moved to a different folder and the previous folder removed (or not accessible anymore). I'm leaving this issue opened until I fix this.

---

> Do you know the painting "GoingUp"?, so, when i enter it, nothing appears in the selection of challenges. how do i make the painting "GoingUp" work and make his challenges appear?

The training room itself was made by the game devs, not by us. We made some small adjustments to make it work better, but there are still a few things that don't work great, such as the Infinite Tower painting not showing the menu correctly.

Even if you don't see the options, you can still use the up/down arrows to select them. They are always in this order:
1. As far as you can!
2. Get there quickly! (250m)
3. As far as you can!
4. Get there quickly! (300m)

(I don't think there's a different between option 1 and 3.)

**Comment by ThomasPoloBelgini** [comment]
ok,thank,but if you want an imagem to send to the devs fix it,that's the image  :
![image](https://github.com/loriswit/rlcm/assets/103902330/6964bcd8-2b54-44a6-a7f9-a905014ce2db)
